### Promise信任问题
* 未来值
* 完成事件
* 信任问题

* 回调编码的信任问题：
    * 调用回调过早
    * 调用回调过晚
    * 调用回调次数过多或过少
    * 未能传递所需的环境和参数
    * 吞掉可能出现的错误和异常

* Promise的特性就是专门针对这些问题提供一个有效的可复用的答案。

### 调用过早 
* 担心：一个任务有时同步完成，有时异步完成，这可能会导致竞态条件。
* 根据定义，Promise就不必担心这种问题，因为即使是立即完成的Promise，也无法被同步观察到。
* 如 new Promise(function(resolve){resolve(42)})---立即完成，但依然不会被同步观察到。
* 也就是说，对一个Promise调用then()的时候**总会异步**。即使这个Promise已经决议。

### 调用过晚
* **只要调用resolve()或reject(),then()就一定会调用**。
* Promise创建对象调用resolve()或reject()时，这个Promise的then()注册的观察回调就会被自动调度。
* 可以确信，这些被调度的回调在下一个异步事件点上一定会被触发。


* 同步查看是不可能的，所以一个同步任务链无法以这种方式运行来实现按照预期有效延迟另一个回调的发生。
* 也就是说，一个Promise决议后，这个Promise上所有的通过then()注册的回调都会在下一个异步时机点上依次被立即调用。
* 这些回调中的任意一个都无法影响或延迟对其他回调的调用。

### 例子1：
```
    // 第一个p.then事件
    p.then(function() {
        p.then(function() {
            console.log("C")
        })
       console.log("A") 
    })

    // 第二个p.then事件
    p.then(function(){
        console.log("B")
    })
```

1. 在事件循环队列中，有两个p.then事件依次等待执行。在事件循环的tick结尾处，有一个任务队列。初始状态下，任务队列是空。
2. 执行第一个p.then事件：
    * 由于**then回调总会异步执行**，所以会在当前tick的任务队列末尾添加一个任务。
    * （异步动作不会导致一个完整的新事件添加到事件循环队列中）
    * 此时，任务队列中存在一个项目：

        // 项目1
        ```
            p.then(function(){
                console.log("C")
            })
            console.log("A")
        ```        
3. 接着执行第二个p.then事件：
    * 同理，由于异步会在当前tick的任务队列末尾再插入一个新项目

    // 项目2
    ```
        console.log("B")
    ```      

    * 此时，当前tick的任务队列中存在了“项目1”和“项目2”两个任务（项目）。

    // 项目1
    ```
        p.then(function(){
            console.log("C")
        })
        console.log("A")
    ```
    // 项目2
     ```
        console.log("B")
    ``` 
4. 事件循环队列中两个p.then事件执行完毕，到了事件循环结尾处。开始执行当前事件循环tick的任务队列：
    * 首先执行项目1：
        * 由于项目1中存在p.then是异步，会引起另一个新任务被添加到同一个任务队列末尾（我们叫它项目3）。
        
            // 项目3
            ```
                console.log("C")
            ```
        * 此时任务队列中存在“项目1”“项目2”“项目3”，3个任务。

            // 项目1
            ```
                p.then(function(){
                    console.log("C")
                })
                console.log("A")
            ```
            // 项目2
            ```
                console.log("B")
            ``` 
            // 项目3
            ```
                console.log("C")
            ``` 
        * 处理完项目1中的p.then之后，会接着执行打印A。
        * 项目1执行结束
    * 接着执行项目2，打印B
    * 最后执行项目3，打印C    




### Promise调度技巧
```
    var p3 = new Promise(function(resolve, reject){
        resolve("B");
    })

    var p1 = new Promise(function(resolve,reject) {
        resolve(p3)
    })

    var p2 = new Promise(function(resolve, reject) {
        resolve("A")
    })

    p1.then(function(v) {
        console.log(v);
    })

    p2.then(function(v) {
        console.log(v);
    })

    // A B
```
> p1不是用立即值而是另一个promise p3 决议，后者本身决议为值“B”。规定的行为是把p3展开到p1，但是是异步地展开。
> 所以在异步任务队列中， p1的回调排在p2的回调之后。
**要避免这样做**-----**不要依赖于不同Promise间回调的顺序和调度**。




### 回调未调用
* **没有任何东西能阻止Promise向你通知它的决议**（如果它决议了的话）。----包括javascript错误。
* 如果对Promise注册了一个完成回调和一个拒绝回调，那么**Promise在决议时总是会调用其中的一个**。

### 调用次数过多
* Promise的定义方式使得它只能被决议一次。
* 如果存在多次调用resolve()或reject()，Promise将**只接受第一次决议**----默默忽略后续任何调用。
* 由于Promise只能被决议一次，所以任何通过then()注册的每个**回调只会被调用一次**。

### 未能传递参数/环境值
* Promise至多只能有一个决议值（完成或拒绝）
* 如果没有任何显式的决议，那么这个值就是 undefined。
* 不管这个值是什么，无论当前或未来，它都会被传给所有注册的（且适当的完成或拒绝）回调。
* 如果resolve()或reject()中传递多个参数----则第一个参数后面的参数都会被忽略。
* 如果要传递多个值，则需要把它们封装在单个值（比如数组或对象）中进行传递。

### 吞掉错误或异常
* 如果拒绝一个Promise并给出一个理由（也就是一个错误消息），这个值就会被传递给拒绝回调。

* Promise中异常
```
    var p = new Promise(function(resolve,reject) {
        foo.bar(); // foo未定义，所以会出错
        resolve(42);
    })

    p.then(
        function fullfilled(data) {
            console.log(data);  // 永远不会到达这里 :(
        }, 
        function rejected(err) {
            console.log(err); // err将会是一个来自 foo.bar()这一选择TypeError异常对象 
        }
    )
```
综上，可以看出**Promise甚至把JavaScript异常也变成了异步行为**。-----进而极大降低了竞态条件出现的可能。

* Promise回调中异常
```
    var p = new Promise(function(resolve,reject) {
        resolve(42);
    })

    p.then(
        function fullfilled(data) {
            foo.bar();
            console.log(data);  // 永远不会到达这里 :(
        }, 
        function rejected(err) {
            console.log(err); // 永远不会到达这里 :( 
        }
    )
```
看起来好像foo.bar()产生的异常被吞掉了。实则是因为我们没有侦听到它。
**p.then()调用本身返回另外一个promise**，-----这个promise将会因TypeError异常而被拒绝。

> 为什么它不是简单地调用我们定义的错误处理函数呢？表面上的逻辑应该是这样啊。如果这样的话就违背了Promise的一条基本原则，即**Promise一旦决议就不可再变**。
> p 已经完成为值42，所以之后查看p的决议时，并不能因为出错就把p再变成一个拒绝。

> 除了违背原则之外，这样的行为也会造成严重的损害。因为假如这个promise p有多个then注册的回调，有些回调会被调用，而有些则不会，情况会非常不透明，难以解释。

### 是可信任的Promise吗
* Promise并没有完全摆脱回调，它们只是改变了传递回调的位置。
* 并不是把回调传给foo()，而是由foo()得到某个东西（外观上看是一个真正的Promise），然后把回调传给这个东西。
* 为什么这就比单纯使用回调更值得信任呢？如何能够确定返回的这个东西实际上就是一个可信任的Promise呢？
* Promise对这个问题已经有一个解决方案-----原生ES6 Promise的解决方案就是 **Promise.resolve(..)**
* **如果向Promise.resolve()传递一个非Promise、非thenable的立即值，就会得到一个用这个值填充的promise**。


* 行为一致的promise:
```
    var p1 = new Promise(function(resolve, reject) {
        resolve(42)
    })

    var p2 = Promise.resolve(42)

    // promise p1 和 promise p2行为完全一样。
    // 但 p1 === p2 为 false
```

* 同一个promise:
```
    var p1 = Promise.resolve(42);
    var p2 = Promise.resolve(p1);

    p1===p2 // true

```
即，**如果向 Promise.resolve()传递一个真正的Promise，就会返回同一个promise**。

* 传递一个thenable值：
```
```

* 总结：
    * 综上，Promise.resolve():
    * 可以接受任何thenable，将其解封为它的非 thenable值。
    * **从Promise.resolve()得到的是一个真正的Promise，是一个可以信任的值**。
    * **如果你传入的已经是真正的Promise，那么你得到的就是它本身**。
    * 所以，通过Promise.resolve()过滤来获得可信任性完全没有坏处。

* 建议：
```
    // 不要只是这么做
    foo(42)
    .then(function(v) {
        console.log(v)
    })

    // 而要这么做
    Promise.resolve(foo(42))
    .then(function(v) {
        console.log(v)
    })
```    

> 对于用Promise.resolve()为所有函数的返回值（不管是不是thenable）都封装一层。
> 另一个好处是，这样做很容易把函数调用规范为定义良好的异步任务。
> 如果foo(42)有时会返回一个立即的值，有时会返回Promise，那么Promise.resolve(foo(42))就能够保证总会返回一个Promise结果。而且避免Zalgo就能得到更好的代码。


