### Promise链
* Promise链不仅是一个表达多步异步序列的**流程控制**
* 还是一个从一个步骤到下一个步骤传递信息的**消息通道**

### Promise链中错误和异常
* 如果这个Promise链中的某个步骤出错了怎么办？
* **错误和异常是基于每个Promise的**，这意味着可能在链的任意位置捕捉到这样的错误，而这个捕捉动作在某种程度上就相当于在这一位置将整条链“重置”回了正常运作。

```
    // 步骤1
    request("http://some.url.1/")

    // 步骤2
    .then(function(response1) {
        foo.bar();  // undefined，出错！

        // 永远不会到达这里
        return request("http://some.url.2/?v=" + response1)
    })

    // 步骤3
    .then(
        function fulfilled(response2) {
            // 永远不会到达这里
        },

        // 捕捉错误的拒绝处理函数
        function rejected(err) {
            console.log(err);
            // 来自 foo.bar()的错误TypeError
            return 42;
        }
    )

    // 步骤4
    .then(function(msg) {
        console.log(msg);   // 42
    })
```

* 第2步出错后，第3步的拒绝处理函数会捕捉到这个错误。
* **拒绝处理函数的返回值**（这段代码中是42），如果有的话，**会用来完成交给下一个步骤（第4步）的promise**。这样这个链现在就回到了完成状态。
* **当从完成处理函数返回一个promise时，它会被展开并有可能延迟下一步骤**。
* 当从**拒绝处理函数返回promise时也是如此**，因此如果第3步中返回的不是42而是一个promise的话，这个promise可能会延迟第4步。
* 调用then()时的完成处理函数或拒绝处理函数如果**抛出异常**，都会**导致（链中的）下一个promise因这个异常而立即被拒绝**。

### Promise默认拒绝处理函数
* 只传完成处理函数时，默认的拒绝处理函数会顶替上来：
```
    var p = new Promise(funciton(resolve, reject) {
        reject("oops")
    })

    var p2 = p.then(
        function fulfilled(){
            // 永远不会到这里
        },

        // 假定的拒绝处理函数，如果省略或者传入任何非函数值
        // function rejected(err){
        //     throw err;
        // }
    )
```
* 默认的决绝处理函数**只是把错误重新抛出**。
* 这会使得 p2（链接的promise）用同样的错误理由拒绝。
* 从本质上来说，**这使得错误可以继续沿着Promise链传播下去**，直到遇到显式定义的拒绝处理函数。

### Promise默认完成处理函数
* 如果没有给then()传递一个适当有效的函数作为完成处理函数参数，还是会有作为替代的一个默认处理函数。
``` 
    var p = Promise.resolve(42);

    p.then(
        // 假定的完成处理函数，如果省略或传入任何非函数值
        // function fulfilled(v) {
        //     return v;
        // },
        null,
        function rejected(err) {
            // 永远不会到达这里
        }
    )
```
* 默认的完成处理函数**只是把接收到的任何传入值传递给下一步步骤**（Promise）而已。
* then(null, function(err){..})这个模式---只处理拒绝（如果有的话），但又把完成值传递下去 ------有一个缩写的API:catch(function(err){..})。